"""
Минимальные стабы типов для модуля `sublime` (Sublime Text 4).

Только тот API, методы которого реально используются в плагине AutoSyntaxByProject.
Полный API — см. официальную документацию Sublime Text.
"""

from typing import Any, Optional

class Settings:
	def get(self, key: str, default: Any = ...) -> Any: ...

class Window:
	def id(self) -> int: ...
	def project_data(self) -> Optional[dict]: ...
	def project_file_name(self) -> Optional[str]: ...

class View:
	def id(self) -> int: ...
	def file_name(self) -> Optional[str]: ...
	def set_syntax_file(self, syntax_path: str) -> bool: ...
	def settings(self) -> Settings: ...
	def window(self) -> Optional[Window]: ...

def load_settings(name: str) -> Settings: ...
